version: 2
updates:
- package-ecosystem: mix
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: "08:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 5
  target-branch: develop
  commit-message:
    prefix: "chore:"
  reviewers:
    - drEnilight
