version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: budgie_api
    container_name: application
    depends_on:
      - postgres
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/budgie.api:cached

  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
