FROM elixir:1.14.4-alpine

ENV MIX_ENV=dev

RUN apk update \
    && apk upgrade --no-cache \
    && apk add --no-cache \
      alpine-sdk \
      inotify-tools \
      expat-dev \
    && mix local.rebar --force \
    && mix local.hex --force

WORKDIR /budgie.api